export const GET_GENERATIONS_TYPE_LIST_START = 'GET_GENERATIONS_TYPE_LIST_START';
export const GET_GENERATIONS_TYPE_LIST_SUCCESS = 'GET_GENERATIONS_TYPE_LIST_SUCCESS';
export const GET_GENERATIONS_TYPE_LIST_FAIL = 'GET_GENERATIONS_TYPE_LIST_FAIL';

export const GET_GENERATIONS_POKEMON_LIST_START = 'GET_GENERATIONS_POKEMON_LIST_START';
export const GET_GENERATIONS_POKEMON_LIST_SUCCESS = 'GET_GENERATIONS_POKEMON_LIST_SUCCESS';
export const GET_GENERATIONS_POKEMON_LIST_FAIL = 'GET_GENERATIONS_POKEMON_LIST_FAIL';

export const GET_POKEMON_TYPE_LIST_START = 'GET_POKEMON_TYPE_LIST_START';
export const GET_POKEMON_TYPE_LIST_SUCCESS = 'GET_POKEMON_TYPE_LIST_SUCCESS';
export const GET_POKEMON_TYPE_LIST_FAIL = 'GET_POKEMON_TYPE_LIST_FAIL';

export const GET_TEAM_POKEMON_START = 'GET_TEAM_POKEMON_START';
export const GET_TEAM_POKEMON_SUCCESS = 'GET_TEAM_POKEMON_SUCCESS';